"""Writes a Markdown SOP (standard operating procedure) doc per incident, plus a
running index at sops/README.md.
"""

from __future__ import annotations

import re
from pathlib import Path

from models import Anomaly, RCAResult

INDEX_MARKER = "<!-- AIOPS_INDEX_APPEND -->"
INDEX_HEADER = (
    "# AIOps Incident SOP Index\n\n"
    "Auto-generated by `aiops scan`. Newest incidents are listed first.\n\n"
    "| Date | Namespace | Workload | Category | Outcome | SOP |\n"
    "|---|---|---|---|---|---|\n"
)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "unknown"


def write_sop(
    anomaly: Anomaly,
    rca: RCAResult,
    outcome: str,
    apply_result: dict | None,
    sops_dir: Path,
) -> Path:
    sops_dir.mkdir(parents=True, exist_ok=True)

    workload = anomaly.workload_name or anomaly.pod_name
    ts = anomaly.detected_at.strftime("%Y%m%d-%H%M%S")
    filename = f"{ts}_{_slug(anomaly.namespace)}_{_slug(workload)}_{_slug(anomaly.category)}.md"
    path = sops_dir / filename

    fix = rca.proposed_fix
    if outcome == "applied":
        fix_result_section = (
            "- **Status:** Applied\n"
            f"- **Result:** {apply_result.get('raw_result') if apply_result else 'n/a'}\n"
        )
    elif outcome == "failed":
        fix_result_section = (
            "- **Status:** Attempted, failed\n"
            f"- **Error:** {apply_result.get('message') if apply_result else 'unknown error'}\n"
        )
    elif outcome == "info_only":
        fix_result_section = "- **Status:** No automated fix available -- manual action required.\n"
    else:
        fix_result_section = "- **Status:** Proposed but not applied (skipped).\n"

    events_block = "\n".join(f"  - {e}" for e in anomaly.related_events) or "  - (none captured)"
    evidence_block = "\n".join(f"- {e}" for e in rca.evidence) or "- (none provided)"
    prevention_block = "\n".join(f"- {p}" for p in rca.prevention) or "- (none provided)"

    content = f"""# Incident: {anomaly.category} in {anomaly.namespace}/{workload}

- **Detected:** {anomaly.detected_at.strftime('%Y-%m-%d %H:%M:%S UTC')}
- **Namespace / Pod / Container:** {anomaly.namespace} / {anomaly.pod_name} / {anomaly.container_name or "(pod-level)"}
- **Workload:** {anomaly.workload_kind or "unknown"} {workload}
- **Category:** {anomaly.category}
- **Severity:** {anomaly.severity}
- **Outcome:** {outcome}

## Symptoms

- Detection signals: `{anomaly.signals}`
- Related events at detection time:
{events_block}

## Root Cause Analysis

{rca.root_cause}

### Evidence

{evidence_block}

## Proposed Fix

- **Tool:** `{fix.tool_name}`
- **Arguments:** `{fix.args}`
- **Rationale:** {fix.rationale}

## Fix Result

{fix_result_section}

## Prevention / Monitoring Recommendations

{prevention_block}
"""
    path.write_text(content)
    return path


def write_index(sops_dir: Path, incidents: list[dict]) -> None:
    if not incidents:
        return

    index_path = sops_dir / "README.md"
    if index_path.exists():
        existing = index_path.read_text()
        if INDEX_MARKER not in existing:
            existing = INDEX_HEADER + INDEX_MARKER + "\n"
    else:
        existing = INDEX_HEADER + INDEX_MARKER + "\n"

    rows = "\n".join(
        f"| {i['date']} | {i['namespace']} | {i['workload']} | {i['category']} "
        f"| {i['outcome']} | [{i['filename']}](./{i['filename']}) |"
        for i in incidents
    )
    updated = existing.replace(INDEX_MARKER, rows + "\n" + INDEX_MARKER)
    index_path.write_text(updated)
